/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aulaandre;

import java.sql.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a1320548
 */
public class PanelMessages extends javax.swing.JPanel {
    private String nickUsuario;

    /**
     * Creates new form PanelMessages
     */
    public PanelMessages(String nickUsuario) {
        initComponents();
        this.nickUsuario=nickUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_Mensagens = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAr_Historico = new javax.swing.JTextArea();
        jBt_Atualizar = new javax.swing.JButton();
        jTxt_Mensagem = new javax.swing.JTextField();
        jBt_Enviar = new javax.swing.JButton();

        jLbl_Mensagens.setText("Mensagens");

        jTxtAr_Historico.setColumns(20);
        jTxtAr_Historico.setRows(5);
        jScrollPane1.setViewportView(jTxtAr_Historico);

        jBt_Atualizar.setText("Atualizar");
        jBt_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_AtualizarActionPerformed(evt);
            }
        });

        jBt_Enviar.setText("Enviar");
        jBt_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_EnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl_Mensagens)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxt_Mensagem)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBt_Enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBt_Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbl_Mensagens)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt_Atualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBt_Enviar)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTxt_Mensagem)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBt_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_AtualizarActionPerformed
        MensagemDao mensagemDao = new MensagemDao();
        try {
            List mensagens = mensagemDao.SelectALL();
            String textoMensagens = new String();
            
            Iterator i = mensagens.iterator();
            while(i.hasNext()) {
                Mensagem msg = (Mensagem) i.next();
                textoMensagens += "\n" + msg.getNick() + ": " + msg.getMensagem();
            }
            jTxtAr_Historico.setText(textoMensagens);
        }
        
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jBt_AtualizarActionPerformed

    private void jBt_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_EnviarActionPerformed
        Mensagem mensagem = new Mensagem();
        mensagem.setMensagem(jTxt_Mensagem.getText());
        mensagem.setNick(nickUsuario);
        mensagem.setDate(Date.valueOf("2015-02-05"));       
        
        MensagemDao mensagemDao = new MensagemDao();
        try {
            mensagemDao.insert(mensagem);
            jTxt_Mensagem.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Falha ao enviar a mensagem.");
        }
        
    }//GEN-LAST:event_jBt_EnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_Atualizar;
    private javax.swing.JButton jBt_Enviar;
    private javax.swing.JLabel jLbl_Mensagens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxtAr_Historico;
    private javax.swing.JTextField jTxt_Mensagem;
    // End of variables declaration//GEN-END:variables
}
