algoritmo "100 asterisco"
// Função :imprimir 100 asterisco na tela
// Autor : Luiz Torres Junior
// Data : 13/09/2013
// Seção de Declarações versao 2.0
var
      contador,quantidade:inteiro
inicio
escreva("Digite a quantidade:")
leia(quantidade)
contador<-0
enquanto (contador<quantidade) faca
 escreva("*")
 contador<-contador+1
fimenquanto
escreva(" = ",quantidade)
fimalgoritmo
