algoritmo "meida semestre"
// Função :
// Autor :
// Data : 29/08/2013
// Seção de Declarações 
var  nota1,nota2,nota3,soma: inteiro
     media:real

inicio
      escreva("Digite a primeira nota:")
      leia(nota1)
      escreva("Digite a segunda nota:")
      leia(nota2)
      escreva("Digite a terceira nota:")
      leia(nota3)
      soma<-nota1+nota2+nota3
      media<-soma/3
      escreva("A media do aluno é:",media)
fimalgoritmo
