/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Main;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import javax.swing.JScrollBar;
import javax.swing.JScrollPane;

/**
 *
 * @author a132067x
 */
public class LojaJFrame extends javax.swing.JFrame {
    Prateleira prateleira;
    /**
     * Creates new form LojaJFrame
     */
    public LojaJFrame(Prateleira prateleira) {
        this.prateleira=prateleira;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        barraMenu = new javax.swing.JMenuBar();
        mnCadastrar = new javax.swing.JMenu();
        miNovo = new javax.swing.JMenuItem();
        mnVisualizar = new javax.swing.JMenu();
        mniVisualizar = new javax.swing.JMenuItem();
        mnRemover = new javax.swing.JMenu();
        mniVisualizar1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnCadastrar.setText("Cadastrar");
        mnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarActionPerformed(evt);
            }
        });

        miNovo.setText("Novo");
        miNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoActionPerformed(evt);
            }
        });
        mnCadastrar.add(miNovo);

        barraMenu.add(mnCadastrar);

        mnVisualizar.setText("Visualizar");

        mniVisualizar.setText("Produtos");
        mniVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarActionPerformed(evt);
            }
        });
        mnVisualizar.add(mniVisualizar);

        barraMenu.add(mnVisualizar);

        mnRemover.setText("Remover");

        mniVisualizar1.setText("Produtos");
        mniVisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizar1ActionPerformed(evt);
            }
        });
        mnRemover.add(mniVisualizar1);

        barraMenu.add(mnRemover);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadastrarActionPerformed

    private void miNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoActionPerformed
        //intancia uma Jpanel para receber a tela de cadastro
        JPanel telaCadastroProduto;
        //Jpanel recebe a tela de cadastro
        telaCadastroProduto = new CadastroProdutoJPanel(prateleira);
        //informa para ter barra de rolagem na jpanel
        JScrollPane jsc = new JScrollPane(telaCadastroProduto, 
                                            JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, 
                                            JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        //infoma que a tela cadastro sera visivel 
        telaCadastroProduto.setVisible(true);
        //coloca o JScrollPanel na JFrame
        this.setContentPane(jsc);
        this.revalidate();
        this.repaint();        
    }//GEN-LAST:event_miNovoActionPerformed

    /**
     *
     * @param prateleira
     */
    
    private void mniVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarActionPerformed
        JPanel telaVisualizarProdutos;
        telaVisualizarProdutos = new VisualizaProdutoCliente(prateleira);
        this.setContentPane(telaVisualizarProdutos);
        this.revalidate();
        this.repaint();        
    }//GEN-LAST:event_mniVisualizarActionPerformed

    private void mniVisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizar1ActionPerformed
        JPanel telaVisualizarProdutos;
        telaVisualizarProdutos = new VisualizarProdutoJPanel(prateleira);
        this.setContentPane(telaVisualizarProdutos);
        this.revalidate();
        this.repaint();     
    }//GEN-LAST:event_mniVisualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LojaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LojaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LojaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LojaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //tenta conectar ao banco
                try{
                //instacia um novo ProdutoDao
                ProdutoDAO produtoDAO = new ProdutoDAO();
                //cria uma lis que recebe um list do ProdutoDAO
                //isso recebe os valores que possui o banco
                List produto = produtoDAO.list();
                
                //uma nova prateleira é instaciada
                Prateleira prateleira = new Prateleira();
                //a prateleira seta os valores da list que recebeu os valores do banco
                prateleira.setPrateleira(produto);
                
                //informa que a LojaCliente deve receber a prateleira como parametro e qu deve ser visivel
                new  LojaClienteJFrame(prateleira).setVisible(true);     
                new LojaJFrame(prateleira).setVisible(true);     
                }
                //caso não encontre o banco
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Não é possivel localizar a aplicação");
            }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem miNovo;
    private javax.swing.JMenu mnCadastrar;
    private javax.swing.JMenu mnRemover;
    private javax.swing.JMenu mnVisualizar;
    private javax.swing.JMenuItem mniVisualizar;
    private javax.swing.JMenuItem mniVisualizar1;
    // End of variables declaration//GEN-END:variables

}
