algoritmo "categoria atraves da idade"
// Função : descubrir a categoria atraves da idade
// Autor :
// Data : 13/09/2013
// Seção de Declarações versao 3.0 atraves de caso
var
    idade:inteiro
inicio
escreva("Digite sua idade")
leia(idade)
escolha idade
caso 2,3,4,5
 escreva("Dente de Leite")
caso 6,7,8,9,10
 escreva("Infantil")
caso 11,12,13,14,15,16
 escreva("Juvenil")
caso 17,18,19,20
 escreva("Sub-20")
outrocaso
 escreva("Adulto")
fimescolha
fimalgoritmo
