algoritmo "categoria atraves da idade"
// Função : descubrir a categoria atraves da idade
// Autor :
// Data : 13/09/2013
// Seção de Declarações versao 3.0 atraves de caso
var
    idade:inteiro
inicio
escreva("Digite sua idade: ")
leia(idade)
escolha idade
caso 2 ate 5
 escreva("Dente de Leite")
caso 6 ate 10
 escreva("Infantil")
caso 11 ate 16
 escreva("Juvenil")
caso 17 ate 20
 escreva("Sub-20")
outrocaso
 escreva("Adulto")
fimescolha
fimalgoritmo
