algoritmo "o maior"
// Função : Descubir o maior de tres numeros
// Autor :  Luiz Torres Junior
// Data : 13/09/2013
// Seção de Declarações v3.0
var a,b,c :inteiro

inicio
escreva("Entre com tres numeros")
leia(a,b,c)
se (a>b) e (a>c) entao
    escreva ("o maior é", a)
senao
se (b>c) entao
    escreva ("o maior é", b)
senao
    escreva ("o maior é", c)
fimse
fimse
fimalgoritmo




