/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package provalp3;

//import javax.swing.JFrame;
import java.util.Collections;
import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author a132067x
 */
public class TelaCadastro extends javax.swing.JFrame {
//é preciso instaciar o arraylista para inicializar
    Estante estante;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(Estante estante) {       
       this.estante = estante;
        initComponents();
        LivroTabelaModelo tabela = new LivroTabelaModelo(estante);
        tbEstante.setModel(tabela);
        //Inicial();
    }  

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        lbAutores = new javax.swing.JLabel();
        lbEdicao = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        lbAnoPublicacao = new javax.swing.JLabel();
        lbISBN = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEstante = new javax.swing.JTable();
        btOrdenarTitulo = new javax.swing.JButton();
        btOrdenarISBN = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        tfTitulo = new javax.swing.JTextField();
        tfAutores = new javax.swing.JTextField();
        tfEdicao = new javax.swing.JTextField();
        tfEditora = new javax.swing.JTextField();
        tfAnoPublicacao = new javax.swing.JTextField();
        tfISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Livro:");

        lbTitulo.setText("Título:");

        lbAutores.setText("Autores:");

        lbEdicao.setText("Edição:");

        lbEditora.setText("Editora:");

        lbAnoPublicacao.setText("Ano de publicação:");

        lbISBN.setText("ISBN:");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        tbEstante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbEstante);

        btOrdenarTitulo.setText("Ordenar tabela por título");
        btOrdenarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarTituloActionPerformed(evt);
            }
        });

        btOrdenarISBN.setText("Ordenar tabela por ISBN");
        btOrdenarISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarISBNActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.setEnabled(false);
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        tfISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfISBNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Livros Cadastrados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbEditora)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbEdicao)
                                        .addGap(32, 32, 32)
                                        .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbISBN)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfISBN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbAnoPublicacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAutores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfAutores)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btOrdenarTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btOrdenarISBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRemover))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutores)
                    .addComponent(tfAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEdicao)
                    .addComponent(lbAnoPublicacao)
                    .addComponent(tfEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEditora)
                    .addComponent(lbISBN)
                    .addComponent(tfEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btLimpar))
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOrdenarTitulo)
                    .addComponent(btOrdenarISBN)
                    .addComponent(btRemover))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        int isbn,ano,edicao;
        String titulo,autores,editora;      
	//intancia o novo livro
        Livro livro = new Livro();
        //o primeiro try serve para nao deixar cadastrar os campos de numeros com o campo texto 
        try{
            isbn = Integer.parseInt(tfISBN.getText());
            ano = Integer.parseInt(tfAnoPublicacao.getText());
            edicao = Integer.parseInt(tfEdicao.getText());
            livro.setAno(ano);
            livro.setEdicao(edicao);
            livro.setIsbn(isbn);
            //o segundo try impede de cadastrar os campos vazios de texto
            try{       
                titulo= tfTitulo.getText();
                autores = tfAutores.getText();
                editora = tfEditora.getText();       
                livro.setAutores(autores);        
                livro.setTitulo(titulo);     
                livro.setEditora(editora);
                estante.add(livro);
                Inicial();        
                LivroTabelaModelo tabela = new LivroTabelaModelo(estante);
                tbEstante.setModel(tabela);   
                this.tbEstante.revalidate();
                this.tbEstante.repaint();
                
            }catch(NullPointerException n) {            
                JOptionPane.showMessageDialog(null, "Preencha todos os campos de Titulo, autores, editora");
            }       
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos de ano, edicao e isbn com numeros validos");
        }
        
        
        
        
              
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        Inicial();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btOrdenarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarTituloActionPerformed
        // TODO add your handling code here:
        CompararPorTitulo comparar = new CompararPorTitulo();
        Collections.sort(estante, comparar);
        LivroTabelaModelo tabela = new LivroTabelaModelo(estante);
        tbEstante.setModel(tabela);   
        this.tbEstante.revalidate();
        this.tbEstante.repaint();
    }//GEN-LAST:event_btOrdenarTituloActionPerformed

    private void tfISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfISBNActionPerformed

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
      
        if(this.tbEstante.getSelectedRow() >=0){
            this.btRemover.setEnabled(true);
        }
        else{
            this.btRemover.setEnabled(false);
        }  
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btOrdenarISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarISBNActionPerformed
        // TODO add your handling code here:
        CompararPorISBN comparar = new CompararPorISBN();
        Collections.sort(estante, comparar);
        LivroTabelaModelo tabela = new LivroTabelaModelo(estante);
        tbEstante.setModel(tabela);   
        this.tbEstante.revalidate();
        this.tbEstante.repaint();
    }//GEN-LAST:event_btOrdenarISBNActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
       int linhaSelecionada = this.tbEstante.getSelectedRow();        
           this.estante.remove(linhaSelecionada);
           this.tbEstante.revalidate();
           JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");          
    }//GEN-LAST:event_btRemoverActionPerformed
public void Inicial(){
        tfTitulo.setText(null);
        tfAutores.setText(null);
        tfEdicao.setText(null);
        tfAnoPublicacao.setText(null); 
        tfEditora.setText(null); 
        tfISBN.setText(null); 
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {  
                Estante estante = new Estante();
                new TelaCadastro(estante).setVisible(true);                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btOrdenarISBN;
    private javax.swing.JButton btOrdenarTitulo;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAnoPublicacao;
    private javax.swing.JLabel lbAutores;
    private javax.swing.JLabel lbEdicao;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTable tbEstante;
    private javax.swing.JTextField tfAnoPublicacao;
    private javax.swing.JTextField tfAutores;
    private javax.swing.JTextField tfEdicao;
    private javax.swing.JTextField tfEditora;
    private javax.swing.JTextField tfISBN;
    private javax.swing.JTextField tfTitulo;
    // End of variables declaration//GEN-END:variables
}
