/*
 * Copyright (C) 2014 
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. Andre See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package controledoacao;

import java.util.Iterator;
import javax.swing.BoundedRangeModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Luiz Torres Junior
 */
public class MostrarTotalDoacoes extends javax.swing.JFrame{
    AbstractTableModel modelo;
    Doacoes doacoes;

    /**
     * Creates new form MostrarTotalDoacoes
     * @param doacoes
     */
    public MostrarTotalDoacoes(Doacoes doacoes) {         
        this.doacoes = doacoes;
        initComponents();
        atualiza();       
    }

    private double calcularTotalDoacoes(Doacoes doacoes) {      
        double total = 0;
        Iterator i = doacoes.iterator();

        while (i.hasNext()) {
            Doacao doacao = (Doacao) i.next();
            total += doacao.getValor();
        }
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bpTotalDoacoes = new javax.swing.JProgressBar();
        lbTotalDoacoes = new javax.swing.JLabel();
        lbZeroReais = new javax.swing.JLabel();
        lbMilhaoReais = new javax.swing.JLabel();
        lbAtualizar = new javax.swing.JButton();
        lbValorAgora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bpTotalDoacoes.setMaximum(100000);

        lbTotalDoacoes.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTotalDoacoes.setText("Total de Doações");

        lbZeroReais.setText("R$ 0,00");

        lbMilhaoReais.setText("R$ 100.000,00");

        lbAtualizar.setText("Atualizar");
        lbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbAtualizarActionPerformed(evt);
            }
        });

        lbValorAgora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorAgora.setText("Ate o momento: R$ 0.0");
        lbValorAgora.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbZeroReais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbValorAgora)
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbAtualizar)
                                    .addComponent(lbMilhaoReais)))
                            .addComponent(bpTotalDoacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(lbTotalDoacoes)
                        .addGap(0, 235, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTotalDoacoes)
                .addGap(38, 38, 38)
                .addComponent(bpTotalDoacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbZeroReais)
                    .addComponent(lbMilhaoReais)
                    .addComponent(lbValorAgora))
                .addGap(18, 18, 18)
                .addComponent(lbAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbAtualizarActionPerformed
        atualiza();
    }//GEN-LAST:event_lbAtualizarActionPerformed
    public void atualiza(){        
        this.setTitle("Progresso das doações");    
        double totalDoacoes = this.calcularTotalDoacoes(doacoes);
        this.bpTotalDoacoes.setValue(Math.round((float) totalDoacoes));
        this.lbValorAgora.setText("Ate o momento: R$ " + totalDoacoes);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bpTotalDoacoes;
    private javax.swing.JButton lbAtualizar;
    private javax.swing.JLabel lbMilhaoReais;
    private javax.swing.JLabel lbTotalDoacoes;
    private javax.swing.JLabel lbValorAgora;
    private javax.swing.JLabel lbZeroReais;
    // End of variables declaration//GEN-END:variables


}
