algoritmo "semnome"
// Função : preencher um vetor vet de 10 posições cos os 10 primeiros numeros impares.
// Autor :Luiz Torres Junior
// Data : 22/11/2013
// Seção de Declarações
var
vet1:vetor [1..10] de inteiro
contador :inteiro

inicio
para contador de 1 ate 10 faca
vet[contador]<-2*i-1
fimpara
escreval()
para contador de 1 ate 10 faca
escreva(vet1[contador])
fimpara
fimalgoritmo
